---
abstract: "provide an alternative version of Param::Validate's"
author:
  - 'Sam Brain <samb@stanford.edu>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Validate-Array
provides:
  Params::Validate::Array:
    file: lib/Params/Validate/Array.pm
    version: 0.03
requires:
  Carp: 0
  Params::Validate: 1.07
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
